### PR TITLE
First pass on developing an policy for the chisel **experimental** convention

### PR DESCRIPTION
**Pull request by chick**
Let the users decide!

### CODE REVIEW

**Comment by ducky64** [comment]
With macros it should be possible to implement an `@experimental` warning. At the minimum, we can do something like the runtime deprecated warnings, and it might also be possible (but difficult) to implement compile-time warnings. Main question would be how to present these warnings:
- Should they be verbose by default, or lean by default? If the latter, the default could be "you're using experimental APIs x, y, z, re-run with --verbose-experimental for more details", where it's reasonable to live with the out-of-the-box (no additional flags - and no code to change later) behavior. But the former makes the experimental warnings more obvious, you have to explicitly "acknowledge" and suppress it.
- Should the warnings be fully suppressible? How, and in a way that avoids the "you need to remove the suppression flags when features graduate from experimental"? A blanket experimental warnings suppression would work, but might not be useful (it'll probably just get spammed everywhere), while suppression on a per-feature basis is more targeted but requires more code changes. One option could be a project-wide experimental suppression flag, so if you need to change code, at least it's just one place.

I do think that the experimental imports get a bit tedious, and given how often they're used it seems like many are fine living on the bleeding edge, and a more lightweight mechanism is useful.

**Comment by ucbjrl** [comment]
I vote for proposal 2 and @ducky64's suggestion to use the `@experimental` annotation to trigger a warning. I think the warning should be lean by default, unless there's an actual API change - this may be too difficult to implement efficiently.

It would be nice if we could use a similar (the same?) mechanism that's used to manage deprecation warnings to suppress `@experimental` warnings.

**Review by ucbjrl — APPROVED** [review]
a vote for proposal 2

**Comment by edwardcwang** [comment]
There's something to be said about warnings getting lost in noise...

**Comment by chick** [comment]
I don't believe there is much of a noise difference between the two proposals, particularly if we create a `@experimental` annotation. Error will be generated either way

**Comment by schoeberl** [comment]
For being more explicit I vote for Proposal 1.

When one imports chisel3.experimental._ then if the experimental feature becomes stable and is moved to chisel3 there is no need for a code change at all, as one imports chisel3._ anyway.

Martin

**Comment by jackkoenig** [comment]
> When one imports chisel3.experimental._ then if the experimental feature becomes stable and is moved to chisel3 there is no need for a code change at all, as one imports chisel3._ anyway.

If it's *moved* you won't have to change code, but then if you did `import chisel3.experimental.feature` your code will break. If the features are copied and deprecated within the `experimental` package, then if you do `import chisel3.experimental._`, your code will break due to duplicate definitions

**Comment by schoeberl** [comment]
> On 27 Aug, 2019, at 21:48, Jack Koenig <notifications@github.com> wrote:
> 
> When one imports chisel3.experimental._ then if the experimental feature becomes stable and is moved to chisel3 there is no need for a code change at all, as one imports chisel3._ anyway.
> 
> If it's moved you won't have to change code, but then if you did import chisel3.experimental.feature your code will break. If the features are copied and deprecated within the experimental package, then if you do import chisel3.experimental._, your code will break due to duplicate definitions
> 
> 
Therefore, the code shall be moved and not copied ;-) Dropping the line chisel3.experimental.feature is a super minimal code change.

Martin

**Pull request merged**
